In [1]:
import torch

## 문제 1

In [2]:
a = torch.rand(3,3)
b = a * 2
c = b.sum()
print(a, b, c) 

tensor([[0.4047, 0.9696, 0.9752],
        [0.9682, 0.5078, 0.6862],
        [0.2718, 0.2523, 0.9407]]) tensor([[0.8094, 1.9391, 1.9504],
        [1.9364, 1.0156, 1.3725],
        [0.5436, 0.5046, 1.8814]]) tensor(11.9529)


## 문제 2

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
a = torch.arange(0,16, dtype=torch.int).view(4,4)
b = a.to(device)
b = b + 5
b.max()

tensor(20, device='cuda:0', dtype=torch.int32)

In [4]:
b

tensor([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]], device='cuda:0', dtype=torch.int32)

## 문제 3

In [5]:
a = torch.eye(5)
b = a + torch.rand(5,5)
c = b**2
d = c.mean(dim=1)
d

tensor([1.3227, 0.5566, 0.8008, 0.7317, 0.8005])

## 문제 4

In [6]:
X = torch.ones(2,2, requires_grad=True)
f = lambda x: 3*x**2 + 2*x + 1
y = f(X)
s = y.sum()
s.backward()
print(X.grad)

tensor([[8., 8.],
        [8., 8.]])


## 문제 5

In [30]:
X = torch.rand(3,3, requires_grad=True)
f = lambda x: x**3 - 4*x**2 + 6*x
Y = f(X)
y = Y.mean()
y.backward()
X.grad

tensor([[0.5089, 0.2950, 0.4574],
        [0.4424, 0.3259, 0.3054],
        [0.2313, 0.3326, 0.4565]])

## 문제 6

In [32]:
X = torch.rand(4,4,requires_grad=True)
f = lambda x: torch.sin(x) + torch.cos(x**2)
Y = f(X)
y = Y.sum()
y.backward()
X.grad


tensor([[-0.5982, -0.7537,  0.4049,  0.9593],
        [ 0.4989,  0.9991,  0.9586,  0.9990],
        [-0.1309,  0.6333,  0.0758, -0.6858],
        [ 0.9892, -0.2060,  0.9986, -0.9479]])