In [1]:
import torch
from torch import nn

In [8]:
model = nn.Linear(3, 1)
print(model.weight, model.bias)
X = torch.rand(5,3)
Y = model(X)
print(Y)

Parameter containing:
tensor([[ 0.3189,  0.3077, -0.5641]], requires_grad=True) Parameter containing:
tensor([-0.1718], requires_grad=True)
tensor([[-0.3179],
        [-0.0925],
        [-0.1055],
        [-0.4862],
        [ 0.1512]], grad_fn=<AddmmBackward0>)


In [15]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3,1)
    def forward(self, x):
        return self.linear(x)
    
model = Model()
print(model.linear.weight, model.linear.bias)
X = torch.rand(5, 3)
Y = model(X)
print(Y)

Parameter containing:
tensor([[0.4109, 0.2780, 0.1353]], requires_grad=True) Parameter containing:
tensor([0.2173], requires_grad=True)
tensor([[0.8456],
        [0.4148],
        [0.8919],
        [0.6298],
        [0.5104]], grad_fn=<AddmmBackward0>)


In [20]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(4, 8)
        self.relu = nn.ReLU()
        self.l2 = nn.Linear(8, 2)
    def forward(self, x):
        x = self.l1(x)
        x = self.relu(x)
        x = self.l2(x)
        return x
model = Model()
print(model.l1.weight, model.l1.bias)
print(model.l2.weight, model.l2.bias)

X = torch.rand(6,4)
Y = model(X)
print(Y)

Parameter containing:
tensor([[-0.3771,  0.4643, -0.2218, -0.1753],
        [ 0.3526, -0.0825, -0.3119, -0.2398],
        [-0.4157,  0.3100, -0.2228,  0.2332],
        [ 0.4869, -0.4060,  0.4978, -0.4744],
        [-0.4609,  0.0035, -0.2563, -0.2514],
        [ 0.4718, -0.3964,  0.2682, -0.3950],
        [ 0.1044, -0.1624,  0.2322,  0.2918],
        [ 0.1110, -0.2727,  0.1052, -0.2372]], requires_grad=True) Parameter containing:
tensor([-0.2342,  0.3218, -0.2754, -0.4829, -0.4038,  0.2282,  0.2746,  0.2776],
       requires_grad=True)
Parameter containing:
tensor([[-0.2566, -0.3051, -0.0331, -0.2996, -0.1406, -0.2549, -0.2782, -0.2740],
        [-0.1776,  0.0006,  0.0683,  0.2985, -0.3229,  0.1521,  0.2474,  0.0649]],
       requires_grad=True) Parameter containing:
tensor([ 0.2273, -0.0848], requires_grad=True)
tensor([[-0.1135,  0.1287],
        [-0.1420,  0.1709],
        [-0.1949,  0.1243],
        [ 0.0576,  0.0666],
        [-0.0613,  0.0806],
        [-0.0263,  0.0771]], grad_fn

In [22]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
    def forward(self, x):
        return self.linear(x)
model = Model()
X = torch.rand(4,3, requires_grad=True)
f = lambda x: x.mean()
yd = f(X)

y = model(X)
mse = ((yd - y)**2).mean()
mse.backward()
model.linear.weight.grad, model.linear.bias.grad 


(tensor([[-0.5854, -0.7421, -0.3936]]), tensor([-1.1263]))

In [23]:
loss_f = nn.MSELoss()

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)
    def forward(self, x):
        return self.linear(x)
model = Model()
X = torch.rand(4,3, requires_grad=True)
f = lambda x: x.mean()
yd = f(X)

y = model(X)
loss = loss_f(yd, y)
loss.backward()
model.linear.weight.grad, model.linear.bias.grad 

/root/.cache/pypoetry/virtualenvs/torchlab-MpxGgwUk-py3.10/lib/python3.10/site-packages/torch/nn/modules/loss.py:538: UserWarning: Using a target size (torch.Size([4, 1])) that is different to the input size (torch.Size([])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


(tensor([[-0.8409, -0.5466, -0.9501]]), tensor([-1.6458]))