In [1]:
import torch

## 문제 1: 파이토치 텐서 생성
다음과 같은 1차원 텐서를 생성하는 코드를 작성하세요:

In [3]:
torch.Tensor([1,2,3,4,5])

tensor([1., 2., 3., 4., 5.])

In [4]:
torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [5]:
x = torch.tensor([1,2,3,4,5])

In [6]:
x

tensor([1, 2, 3, 4, 5])

In [7]:
x.dtype

torch.int64

## 문제 2: 텐서의 기본 연산
다음 두 개의 텐서 a와 b를 더하는 코드를 작성하세요:

In [8]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

In [9]:
a + b

tensor([5, 7, 9])

In [10]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

c = a*b
c

tensor([ 4, 10, 18])

## 문제 4: 텐서의 행렬 곱셈
다음 두 개의 2차원 텐서 A와 B의 행렬 곱셈(matrix multiplication)을 수행하는 코드를 작성하세요:

In [12]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[5,6],[7,8]])
C = torch.matmul(A,B)
C

tensor([[19, 22],
        [43, 50]])

## 문제 5: 텐서의 모양 변경 (reshape)
다음 텐서 x의 모양을 (2, 3)으로 변경하는 코드를 작성하세요:

In [13]:
x = torch.tensor([1,2,3,4,5,6])
x = x.view(2,3)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

## 문제 6: 텐서의 데이터 타입 변경
다음 텐서 x의 데이터 타입을 float으로 변경하는 코드를 작성하세요:

In [16]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
x = x.float()
x

tensor([1., 2., 3., 4., 5., 6.])