In [23]:
import torch
from lib import apply_markdown_format as amd

## 문제 17: 텐서의 역전파(Backpropagation) 준비하기
다음 텐서 x에 대해 역전파를 수행할 수 있도록 준비하는 코드를 작성하세요:
```python
x = torch.tensor([1.0, 2.0, 3.0])
```

In [5]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print(x)

tensor([1., 2., 3.], requires_grad=True)


In [8]:
# 역전파 사용 예시1
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x * 5 # y = [2x_1, 2x_2, 3x_3]
z = y.sum() # z = 2x_1 + 2x_2 + 3x_3
print(x, y, z)
z.backward() # derivation by backprop

print(x.grad)

tensor([1., 2., 3.], requires_grad=True) tensor([ 5., 10., 15.], grad_fn=<MulBackward0>) tensor(30., grad_fn=<SumBackward0>)
tensor([5., 5., 5.])


In [11]:
# 역전파 사용 예시1
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
y = x * 9 # y = [2x_1, 2x_2, 3x_3]
z = y.mean() # z = 2x_1 + 2x_2 + 3x_3
print(x, y, z)
z.backward() # derivation by backprop

print(x.grad)

tensor([1., 2., 3.], requires_grad=True) tensor([ 9., 18., 27.], grad_fn=<MulBackward0>) tensor(18., grad_fn=<MeanBackward0>)
tensor([3., 3., 3.])


## 문제 18: 텐서의 특정 차원 기준으로 합계 계산
다음 텐서 x에서 각 열(column)의 합계를 계산하는 코드를 작성하세요:
```python
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
```

In [14]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x.sum(dim=0) 

tensor([5, 7, 9])

## 문제 19: 텐서의 요소별 제곱근 계산
다음 텐서 x의 각 요소의 제곱근을 계산하는 코드를 작성하세요:
```python
x = torch.tensor([4.0, 9.0, 16.0])
```

In [17]:
x = torch.tensor([4.0, 9.0, 16.0])
torch.sqrt(x)

tensor([2., 3., 4.])

## 문제 20: 텐서의 특정 값 인덱스 찾기
다음 텐서 x에서 값이 5인 첫 번째 위치의 인덱스를 찾는 코드를 작성하세요:

```python
x = torch.tensor([3, 5, 7, 5, 9])
```

In [35]:
x = torch.tensor([3, 5, 7, 5, 9])
torch.argwhere(x==5)[0].item()

1

In [41]:
x = torch.tensor([3, 5, 7, 5, 9])
torch.nonzero(x==5,as_tuple=False)[0].item()

1

## 문제 21: 텐서의 요소별 지수 함수 계산
다음 텐서 x의 각 요소에 지수 함수를 적용하고, 결과 텐서의 각 요소의 합계를 계산하는 코드를 작성하세요:

```python
x = torch.tensor([0.0, 1.0, 2.0])
```

In [42]:
x = torch.tensor([0.0, 1.0, 2.0])
y = torch.exp(x)
y.sum()

tensor(11.1073)

## 문제 22: 텐서의 표준화
다음 텐서 x의 각 요소를 표준화하여 평균이 0, 표준편차가 1이 되도록 변환하는 코드를 작성하세요:

```python
x = torch.tensor([1.0, 2.0, 3.0, 4.0, 5.0])
```

In [45]:
y = x - x.mean()
y = y / x.std()
y.mean(), y.std()

(tensor(0.), tensor(1.))

## 문제 23: 텐서의 차원 추가 및 전치
다음 텐서 x에 차원을 추가하여 (3, 1) 형식으로 만든 후, 전치하여 (1, 3) 형식의 텐서로 변환하는 코드를 작성하세요:

```python
x = torch.tensor([1, 2, 3])
```

In [49]:
x = torch.tensor([1, 2, 3])
y = x.view(3,1)
z = y.T
z.shape

torch.Size([1, 3])