In [1]:
import torch

## 문제 25: 자동 미분을 사용한 기울기 계산
다음 함수 ( f(x) = x^2 + 2x + 1 )에 대해 ( x = 3.0 )일 때의 기울기를 계산하는 코드를 작성하세요. 여기서 자동 미분을 사용하여 기울기를 구해야 합니다.

In [3]:
x = torch.tensor([3.0], requires_grad=True)
y = x**2 + 2*x + 1
y.backward()
x.grad

tensor([8.])

## 문제 26: 여러 텐서의 기울기 계산
다음 함수 ( f(x, y) = x^2 + y^2 )에 대해 ( x = 1.0 )과 ( y = 2.0 )일 때의 기울기를 각각 계산하는 코드를 작성하세요.

In [5]:
x = torch.tensor([1.0], requires_grad=True)
y = torch.tensor([2.0], requires_grad=True)
z = x**2 + y**2
z.backward()
x.grad, y.grad

(tensor([2.]), tensor([4.]))

## 문제 27: 기울기 초기화 후 재계산
다음 함수 ( f(x) = x^3 )에 대해 ( x = 2.0 )일 때의 기울기를 계산한 후, 기울기를 초기화하고 ( x = 3.0 )일 때 다시 기울기를 계산하는 코드를 작성하세요.

In [8]:
x = torch.tensor([2.0], requires_grad=True)
fx = x**3
fx.backward()
print(x.grad)

x[0] = 3.0
fx.backward()
x.grad

tensor([12.])


RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.