In [2]:
import torch

## 문제 1: 파이토치 텐서 생성
다음과 같은 1차원 텐서를 생성하는 코드를 작성하세요:

In [3]:
torch.Tensor([1,2,3,4,5])

tensor([1., 2., 3., 4., 5.])

In [4]:
torch.tensor([1,2,3,4,5])

tensor([1, 2, 3, 4, 5])

In [5]:
x = torch.tensor([1,2,3,4,5])

In [6]:
x

tensor([1, 2, 3, 4, 5])

In [7]:
x.dtype

torch.int64

## 문제 2: 텐서의 기본 연산
다음 두 개의 텐서 a와 b를 더하는 코드를 작성하세요:

In [8]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

In [9]:
a + b

tensor([5, 7, 9])

In [10]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

c = a*b
c

tensor([ 4, 10, 18])

## 문제 4: 텐서의 행렬 곱셈
다음 두 개의 2차원 텐서 A와 B의 행렬 곱셈(matrix multiplication)을 수행하는 코드를 작성하세요:

In [12]:
A = torch.tensor([[1,2],[3,4]])
B = torch.tensor([[5,6],[7,8]])
C = torch.matmul(A,B)
C

tensor([[19, 22],
        [43, 50]])

## 문제 5: 텐서의 모양 변경 (reshape)
다음 텐서 x의 모양을 (2, 3)으로 변경하는 코드를 작성하세요:

In [13]:
x = torch.tensor([1,2,3,4,5,6])
x = x.view(2,3)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

## 문제 6: 텐서의 데이터 타입 변경
다음 텐서 x의 데이터 타입을 float으로 변경하는 코드를 작성하세요:

In [16]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
x = x.float()
x

tensor([1., 2., 3., 4., 5., 6.])

## 문제 7: 텐서의 합계
다음 텐서 x의 모든 요소의 합을 계산하는 코드를 작성하세요:

In [17]:
x = torch.tensor([1, 2, 3, 4, 5, 6])
x.sum()

tensor(21)

## 문제 8: 텐서에서 특정 요소 접근
다음 텐서 x에서 두 번째 요소를 가져오는 코드를 작성하세요:

In [18]:
x = torch.tensor([10, 20, 30, 40, 50])
x[1]

tensor(20)

## 문제 9: 텐서의 요소별 제곱
다음 텐서 x의 각 요소의 제곱을 계산하는 코드를 작성하세요:

In [19]:
x = torch.tensor([1,2,3,4,5])
x ** 2

tensor([ 1,  4,  9, 16, 25])

In [24]:
x = torch.tensor([1, 2, 3, 4, 5])
x = x.float()
mx = torch.mean(x)
mx

tensor(3.)

## 문제 11: 텐서의 차원 추가
다음 텐서 x의 차원을 하나 추가하여 (5, 1) 형식의 텐서를 만드는 코드를 작성하세요:
```rust
x = torch.tensor([1, 2, 3, 4, 5])
````

In [26]:
x = torch.tensor([1,2,3,4,5])
x = x.view(5,1)
x

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

## 문제 12: 텐서의 요소별 최대값 찾기
다음 텐서 x에서 각 요소별로 최대값을 찾는 코드를 작성하세요:

In [29]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
m = torch.max(x, dim=1)
m.values

tensor([3, 6])

## 문제 13: 텐서의 요소별 최소값 찾기
다음 텐서 x에서 각 요소별로 최소값을 찾는 코드를 작성하세요:
```rust
x = torch.tensor([[7, 8, 9], [10, 11, 12]])
```

In [4]:
x = torch.tensor([[7, 8, 9], [10, 11, 12]])
x = torch.min(x, dim=-1)
x.values

tensor([ 7, 10])

## 문제 14: 텐서의 평균값을 특정 차원 기준으로 계산하기
다음 텐서 x에서 각 행의 평균값을 계산하는 코드를 작성하세요:

In [6]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
x = x.float()
x.mean(dim=1)

tensor([2., 5.])

## 문제 15: 텐서를 GPU로 이동하기
다음 텐서 x를 GPU로 이동시키는 코드를 작성하세요. (GPU가 없으면 CPU에 남아있게 해도 됩니다.)

In [17]:
x = torch.tensor([1,2,3,4,5])
device = "cuda" if torch.cuda.is_available() else "cpu"
x = x.to(device)
x

tensor([1, 2, 3, 4, 5], device='cuda:0')